name: Rollback versions
on:
  #- push
 push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  rollback-please:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Check if rollback
      run: |
        message=$(echo "${{ github.event.head_commit.message }}")
        is_rollback=$(echo "$message" | { grep "Merge pull request #" || echo ""; } | { grep "rollback-branch" || echo ""; })
        if [ -z "$is_rollback" ]; then
          echo "Not rollback. Exiting."
          exit 0
        fi
        echo "Commit message: $message"
        broken_version="v"$(echo "$message" | tail -n1 | sed 's/.*Rollback version from //' | sed 's/ to.*//')
        echo "Broken version: $broken_version"
        prev_version="v${message##*v}"
        echo "Previous version: $prev_version"
        gh release edit $prev_version --latest
        gh release edit $broken_version --title ${broken_version}-broken