name: A.
on:
  workflow_call:
    inputs:
      v:
        required: true
        type: string
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "${{ inputs.v }}"