name: Push to main
on:
  - push

env:
  GH_TOKEN: ${{ github.token }}
  RELEASE_TYPE: simple
#  APP_NAME: 'aaaa'
#  DOCKER_REGISTRY: 'bbbb'
#  GITHUB_TOKEN: 'a'

jobs:
  b:
    uses: ./.github/workflows/a.yaml
    with:
      v: $RELEASE_TYPE