name: Push to main
on:
  - push

env:
  GH_TOKEN: ${{ github.token }}
  RELEASE_TYPE: simple
#  APP_NAME: 'aaaa'
#  DOCKER_REGISTRY: 'bbbb'
#  GITHUB_TOKEN: 'a'

jobs:
  c:
    runs-on: ubuntu-latest
    outputs:
      cc: ${{ env.RELEASE_TYPE }}
  b:
    uses: ./.github/workflows/a.yaml
    needs:
      - c
    with:
      v: ${{ needs.c.outputs.cc }}