name: b

on:
  - push
  #push:
  #  branches:
  #    - main

env:
  APP_NAME: 'toy-service'
  DOCKER_REGISTRY: 'innoplatform.azurecr.io'
  ARGOCD_REPOSITORY: 'git.dg-i.net/azde/inno/inno-fpp/orchestration.git'
  RELEASE_TYPE: 'node'
  GH_TOKEN: ${{ github.token }}

jobs:
  bb:
    name: job_bb
    runs-on: ubuntu-latest
    outputs:
      argocd_repository: "${{ env.ARGOCD_REPOSITORY }}"
    steps:
      - name: step_b
        id: step_b
        run: echo "step_b."
          
  b:
    name: job_b
    uses: ./.github/workflows/a.yaml
    with:
      # why needs.choose-action instead of going directly to env variable?
      # Because github actions doesn't like to pass env variables on "with".
      argocd_repository: ${{ needs.bb.outputs.ARGOCD_REPOSITORY }}
      file_path: './orchestration/production/toy-service.yaml'
      yaml_key_path: '["spec", "source", "targetRevision"]'
    needs:
      - bb