name: Push to main
on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}
  RELEASE_TYPE: simple
#  APP_NAME: 'aaaa'
#  DOCKER_REGISTRY: 'bbbb'
#  GITHUB_TOKEN: 'a'

jobs:
  d:
    runs-on: ubuntu-latest
    outputs:
      cc: ${{ env.RELEASE_TYPE }}
  b:
    uses: ./.github/workflows/a.yaml
    needs:
      - d
    with:
      v: ${{ needs.d.outputs.cc }}