name: Push to main
on:
  - push

env:
  GH_TOKEN: ${{ github.token }}
  RELEASE_TYPE: simple
#  APP_NAME: 'aaaa'
#  DOCKER_REGISTRY: 'bbbb'
#  GITHUB_TOKEN: 'a'

jobs:
  c:
    runs-on: ubuntu-latest
    outputs:
      cc: ${{ env.ARGOCD_REPOSITORY }} # ${{ steps.c.outputs.c }}
    steps:
      - name: c
        id: c
        run: |
          echo "C=C." # >> $GITHUB_OUTPUT
  b:
    uses: ./.github/workflows/a.yaml
    needs:
      - c
    with:
      v: ${{ needs.c.outputs.cc }}