name: Push to main
on:
  - push

env:
  GH_TOKEN: ${{ github.token }}
  RELEASE_TYPE: simple
#  APP_NAME: 'aaaa'
#  DOCKER_REGISTRY: 'bbbb'
#  GITHUB_TOKEN: 'a'

jobs:
  c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Change branch to branch-1
        run: git checkout branch-1
      - run: |
          git config --global user.name "actions-bot"
          git config user.email 'github-actions-bot@google.com'
          pr_title="Rollback version from 2 to 1"
          pr_body="If current version is not working, use this pull request to revert the version deployed from 2 to 1.
            This will **not** revert changes on main branch. What it does:
            - Change version files to place the previous version.
            - Update argocd deployment so it uses the previous version again."
          gh pr create --title "$pr_title" --body "$pr_body"