name: Always run this

on:
  - push

env:
  yaml_inside_yaml_key_path: "No_VaLuE_sO-nO_uSeX"

jobs:
  run-this:
    name: run-this
    runs-on: ubuntu-latest
    outputs:
      argocd_repository: "${{ env.ARGOCD_REPOSITORY }}"
    steps:
      - name: step 1
        id: step_1
        if: ${{ env.yaml_inside_yaml_key_path == 'No_VaLuE_sO-nO_uSe' }}
        run: echo "Variable not set..."
      - name: step 2
        id: step_2
        if: ${{ env.yaml_inside_yaml_key_path != 'No_VaLuE_sO-nO_uSe' }}
        run: echo "variable set..."