name: Push to main A
on:
  push:
    paths:
      - "src_a/**"
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}
  RELEASE_TYPE: simple

jobs:
  release-please:
    name: "Release please"
    uses: ./.github/workflows/release-please.yaml
    with:
      package: experiment_a
      path: src_a/
      release-type: simple
      version-file: src_a/version.txt

  check-release-please:
     name: "Check release-please"
     needs:
       - release-please
     runs-on: ubuntu-latest
     steps:
      - name: "Generate the image tag"
        id: image_tag
        run: |
           echo "Released -> ${{ needs.release-please.outputs.release_created }}"
           echo "Version -> ${{ needs.release-please.outputs.version_tag }}"
