name: Push to main A
on:
  push:
    paths:
      - "src_a/**"
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}
  RELEASE_TYPE: simple

jobs:
  release-please:
    name: "Release please"
    uses: ./.github/workflows/release-please.yaml
    with:
      package: experiment_a
      path: src_a/
      release-type: simple
      version-file: src_a/version.txt
