name: Push to main B
on:
  push:
    paths:
      - "src_b/**"
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}
  RELEASE_TYPE: simple

jobs:
  release-please:
    name: "Release please"
    uses: ./.github/workflows/release-please.yaml
    with:
      release-type: simple
      package: experiments_b
      path: src_b
      version-file: src_b/version.txt
      use-monorepo-tags: true