name: Push to main
on:
  push:
    branches:
      - main

env:
  APP_NAME: 'aaaa'
  DOCKER_REGISTRY: 'bbbb'
  #GITHUB_TOKEN: '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'

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created || false }}
      version_tag: "${{ steps.release.outputs.release_created && format('{0}.{1}.{2}',steps.release.outputs.major,steps.release.outputs.minor,steps.release.outputs.patch) || steps.package-json-version.outputs.value }}"
    steps:
    - uses: google-github-actions/release-please-action@v3
      id: release
      with:
        release-type: simple

    - name: Checkout code
      uses: actions/checkout@v3

  rollback-latest-release:
    name: ArgoCD Rollback Latest Deployment to Production
    runs-on: ubuntu-latest
    needs:
      - release-please
    steps:
    - run: echo "hello world"    

