name: Push to main B
on:
  push:
    paths:
      - "src_b/**"
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}
  RELEASE_TYPE: simple

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created || false }}
      version_tag: "${{ steps.release.outputs.release_created && format('{0}.{1}.{2}',steps.release.outputs.major,steps.release.outputs.minor,steps.release.outputs.patch) || steps.package-json-version.outputs.value }}"
    steps:
    - uses: google-github-actions/release-please-action@v3
      id: release
      with:
        release-type: ${{ env.RELEASE_TYPE }}
        package-name: experiments_b
        version-file: src_b/version.txt
        monorepo-tags: true
    - name: Checkout code
      uses: actions/checkout@v3
