name: Rollback versions
on:
 - push

env:
  #APP_NAME: 'aaaa'
  #DOCKER_REGISTRY: 'bbbb'
  #GITHUB_TOKEN: 'aaaa'
  GH_TOKEN: ${{ github.token }}

jobs:
  # maybe needs a step to check if release was a rollback or no
  rollback-please:
    runs-on: ubuntu-latest
    steps:
    #- name: Checkout code
    #  uses: actions/checkout@v3
    #- name: Checkout to branch release-rollback
    #  run: git checkout -b 
    #- name: checkout code to previous release version
    #  run: git checkout v1.0.0'
    - name: Check if rollback
      run: |
        was_rollback=$(echo "${{ github.event.head_commit.message }}" | grep 'Merge pull request #' | grep rollback-branch)
        if [ -z was_rollback ]; then
          echo "Not rollback. Exiting."
          exit 0
        fi
        echo "Rollback."

