name: Create rollback pull request
on:
  release:
    types: [published, released, prereleased]

env:
  APP_NAME: 'aaaa'
  DOCKER_REGISTRY: 'bbbb'
  #GITHUB_TOKEN: 'aaaa'

jobs:
  # maybe needs a step to check if release was a rollback or no
  rollback-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    #- name: Checkout code
    #  uses: actions/checkout@v3
    - name: Check previous version
      run: echo "${{ github.repository }}" | gh release list
    #- name: checkout code to previous release version
    #  run: git checkout v1.0.0'

