name: Rollback versions
on:
  - push
 #push:
 #   branches:
 #     - main

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  # maybe needs a step to check if release was a rollback or no
  rollback-please:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Check if rollback
      run: |
        message=$(echo "${{ github.event.head_commit.message }}")
        is_rollback=$(echo "$message" | { grep "Merge pull request #" || echo ""; } | { grep "rollback-branch" || echo ""; })
        if [ -z "$is_rollback" ]; then
          echo "Not rollback. Exiting."
          exit 0
        fi
        echo "Commit message: $message"
        last_line=$(echo "$message" | tail -n1)
        echo "$last_line"
        versions=$(echo "$last_line" | sed 's/.*Rollback version from //')
        echo "$versions"
        broken_version="v"$(echo "$message" | tail -n1 | sed 's/.*Rollback version from //' | sed 's/ to.*//')
        echo "Broken version: $broken_version"
        prev_version="v${message##*v}"
        echo "Previous version: $prev_version"
        #gh release edit $prev_version --latest
        #gh release edit $broken_version --title ${broken_version}-broken

# Merge pull request #59 from Joao-Andrade/rollback-branch
# Rollback version from 1.19.0 to v1.18.0