name: update yaml

on:
  push:
    paths:
      - ".github/workflows/update_yaml.yaml"
      - "src_c/yaml.yml"

jobs:
  update-yaml:
    name: update the yaml
    runs-on: ubuntu-latest
    outputs:
      argocd_repository: "${{ env.ARGOCD_REPOSITORY }}"
    steps:
      - uses: actions/checkout@v3
      - name: step 1
        id: step_1
        run: cat src_c/yaml.yaml
      - name: Patch spec.sampleVersion
        uses: Joao-Andrade/patch-yaml-inside-yaml@main
        with:
          documentFile: src_c/yaml.yaml
          yamlPath: spec.sampleVersion
          newValue: "1.0.0"
      - name: Patch spec.source.helm.values-image.tag
        uses: Joao-Andrade/patch-yaml-inside-yaml@main
        with:
          documentFile: src_c/yaml.yaml
          yamlPath: spec.source.helm.values
          yamlInsideYamlPath: image.tag
          newValue: "1.0.0"
      - name: Patch spec.sources[chart=chart1].version
        uses: Joao-Andrade/patch-yaml-inside-yaml@main
        with:
          documentFile: src_c/yaml.yaml
          yamlPath: spec.sources[?(@.chart="chart1")].version
          newValue: "1.0.0"
      - name: Patch spec.source.helm2.values-images[app=a].tag
        uses: Joao-Andrade/patch-yaml-inside-yaml@main
        with:
          documentFile: src_c/yaml.yaml
          yamlPath: spec.source.helm2.values
          yamlInsideYamlPath: "images[?(@.app='a')].tag"
          newValue: "1.0.0"
      - name: Patch spec.sources[chart=chart2].values-image.tag
        uses: Joao-Andrade/patch-yaml-inside-yaml@main
        with:
          documentFile: src_c/yaml.yaml
          yamlPath: spec.sources[?(@.chart='chart2')].values
          yamlInsideYamlPath: images.tag
          newValue: "1.0.0"
      - name: Patch spec.sources[chart=chart2].values-images[app=c].tag
        uses: Joao-Andrade/patch-yaml-inside-yaml@main
        with:
          documentFile: src_c/yaml.yaml
          yamlPath: spec.sources[?(@.chart='chart2')].values
          yamlInsideYamlPath: images[?(@.app='c')].tag
          newValue: "1.0.0"
